name: release

on:
    workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
