name: workflow.yml
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}


